### ISSUE TITLE
Tutorial feedback

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1082]
# https://lamin.ai/docs/tutorial

General feedback: I love the tiny drop downs and the tips that provide more background and further links. Great! However, I feel like sometimes too much context is assumed why we're doing certain things and why they're helpful later. The tutorial is rich with code and minimal of explanations. I personally would increase the text proportion by 10%. Generally, the tutorial is also very long and we could consider making a bit more of its content "optional" by moving it into drop downs.

- [x] "LaminDB registry of transforms ([Transform](https://64e5ffa24a3b2b0d5e38d413--lamindb-qnwk.netlify.app/lamindb.transform#lamindb.Transform)) makes it easy to link data to transforms." -> reads a bit convoluted.
- [x] "Let’s call the code that generated a batch of data a transform. It could be a pipeline, a notebook or an app upload." -> "we call"
- [x] Uhm, the result is empty?
![image](https://github.com/laminlabs/lamindb/assets/21954664/476ec6a3-2677-4401-8614-835b3282d9de)

- [x] Too many line breaks
![image](https://github.com/laminlabs/lamindb/assets/21954664/6ff7386f-305f-461f-8718-687aafef5475)
- [x] Introduce django syntax with a dropdown here already?
![image](https://github.com/laminlabs/lamindb/assets/21954664/c9ce6b01-6ab7-4e4f-b0f7-3f4aad0a52a9)
- [x] Maybe it's just me, but it's not clear how this dataset comes with labels
![image](https://github.com/laminlabs/lamindb/assets/21954664/203377fc-180f-4e95-8a82-4a1bc571786c)
- [x] "Why label" sounds nicer I think
![image](https://github.com/laminlabs/lamindb/assets/21954664/984658ae-707f-48ab-9a9b-6b0d93edbe76)
- [x] Why a feature when we just labeled it? What's the benefit of this? Unclear at first glance...
![image](https://github.com/laminlabs/lamindb/assets/21954664/9b856f3b-a589-41e9-bd6e-f969850b6222)
- [x] I'd appreciate a "what happened under the hood" here. Does this concatenate the datasets?
![image](https://github.com/laminlabs/lamindb/assets/21954664/59fddba3-c999-4a7e-a695-aff2008cfdb7)
- [x] The section "Validate records upon creation" could be a dropdown to make the tutorial shorter
- [x] Consider merging the "label" code cells into the ones just above them for less scrolling
![image](https://github.com/laminlabs/lamindb/assets/21954664/8ce92501-c0d1-487c-bc1c-1f60c7ee37a6)
- [x] Link to verbosity level docs. What levels do we have?
![image](https://github.com/laminlabs/lamindb/assets/21954664/ac944d53-a7e8-4cfe-b8ea-21f8a616e7b7)

**Comment by falexwolf** [comment]
https://laminlabs.slack.com/archives/C04M3R0DM3Q/p1692794656743729

**Comment by falexwolf** [comment]
Thanks, again, Lukas!

Working through this now based on the new tutorial!

**Comment by falexwolf** [comment]
Re tutorial part 2:

Fully agreed on almost everything and made the changes [here](https://github.com/laminlabs/lamindb/pull/1093/commits/614383821b36acad1499ff77bb2e239e5ef25b0b).

Just wrapping my head around this one point, here. I'd love to show an output, which isn't possible in a dropdown. But I also agree that for most people it's a "nice to have" (for me it's one of the most important features). So, maybe we could just manually capture some output like we do in docstring examples in the next iteration.
<img width="709" alt="image" src="https://github.com/laminlabs/lamindb/assets/16916678/c29ffa2a-698a-41ff-84c4-f5cd4a3ad8ab">
<img width="792" alt="image" src="https://github.com/laminlabs/lamindb/assets/16916678/ce648816-12fc-4ca1-892c-a9c82284d8b6">

**Comment by falexwolf** [comment]
There are a few more changes in https://github.com/laminlabs/lamindb/pull/1093, and I'd now move this into the prod docs at lamin.ai.

If you see more quirks or confusing things, just make a PR and we'll frequently move it into production!

**Comment by Zethson** [comment]
Awesome, thank you very much!

`:::{dropdown} Why does LaminDB model feature sets, not just features?`

is great!
