### ISSUE TITLE
laminDB and AnnDataCollection

### ISSUE THREAD

**Issue by jkobject** [laminlabs/lamindb#1306]
Is there something akin to an AnnDataCollection on lamin or I should use AnnDataCollection myself?

The goal is to load oom many AnnDatas as one and then run specific query on them based on their index. 

One more question you might have the answer to: out of memory / backed AnnDataCollections are indexed, right?

Thanks already for the all the help!

**Comment by falexwolf** [comment]
Hey Jeremie, @Koncopd has prepared some material surveying different data loaders in the field.

We have a meeting to discuss it at 4:30 pm today and will send it your way.

But @Koncopd - you could maybe also expound here right away on why `AnnCollection` itself is probably not the right fit; depending on your specific setup.

**Comment by jkobject** [comment]
I will be there!

**Comment by Koncopd** [comment]
That depends on what really should be done. Some problems with it:
`AnnCollection` uses the standard anndata backed mode, so only `.X` is backed, this can be problematic if there are layers etc.
It allows to access only observational related parts (`.obs`, `.obsm` etc).
`AnnLoader`, which is a dataloader using `AnnCollection`, can't do weighted sampling.

But of course it is possible to use `AnnCollection` by staging the files and passing the paths from .stage() to `AnnCollection`.

**Comment by falexwolf** [comment]
> I will be there!

Do you mean you'd like to join the meeting? If so, happy to forward the invite!

**Comment by Koncopd** [comment]
What do you mean by indexing here? `AnnCollection` takes several `AnnData` objects and virtually concatenates them so ou can access `.X,` `.layers`, `.obs`, `.obsm` etc by subsetting the `AnnColection` object.

I agree, it is pretty straightforward to add weighted sampling there by just replacing [here](https://github.com/scverse/anndata/blob/d4cde5c708c884703124a40d7ce48a7e52805859/anndata/experimental/pytorch/_annloader.py#L35) shuffling of indices with `np.random.choice` with weights.

**Comment by jkobject** [comment]
> What do you mean by indexing here? AnnCollection takes several AnnData objects and virtually concatenates them so you can access .X, .layers, .obs, .obsm etc by subsetting the AnnCollection object.

I meant to say that even if all of the AnnData objects are backed. I can do something like requesting row index [1,450, 1480] and it would retrieve them without loading the anndatas in memory and only getting these elements fast

**Comment by Koncopd** [comment]
Ok, i see, yes, it is possible. However, as i wrote above, the standard backed mode in `anndata` (which also` AnnCollection` uses) allows only `.X` to be backed, everything else is loaded into memory.

**Comment by jkobject** [comment]
I understand, my guess is that it might be ok to load that many dataframes in memory (?) Then there is the option to update backed AnnDatas so that the obs is stored as a polars dataframe and the collection just makes concatenations of those. this way nothing is in memory..

**Comment by Koncopd** [comment]
Not sure if anndata supports polars dataframes. 
If you need only to iterate through a list of adatas with weighted sampling, there is no need to actually use `AnnCollection`, we can make a custom dataloader, that can hold everything on disk and load only the required indices or batches into memory.

**Comment by jkobject** [comment]
> we can make a custom dataloader, that can hold everything on disk and load only the required indices or batches into memory.
yes but it seems almost more complex to recreate mechanism to load and concatenate the different elements of the h5ads than updating anndata's read() function.
Also, it means you kinda move away from having something that neatly fits within the anndata framework.

**Comment by Koncopd** [comment]
It is not that complicated if you need only iterating and sampling.

**Comment by falexwolf** [comment]
(Apologies, I was at a family event during the day - I'm back now and forwarded the meeting link)

**Comment by falexwolf** [comment]
Thanks to @Koncopd, in lamindb 0.62, there now is an easy way to create a weighted sampler for h5ad- and zarr-backed AnnData collections.

A small use case is documented here: https://lamin.ai/docs/scrna5

Here is the [API reference](https://lamin.ai/docs/lamindb.dataset#lamindb.Dataset.mapped)
