### ISSUE TITLE
running a preprocess on a dataset (transform?)

### ISSUE THREAD

**Issue by jkobject** [laminlabs/lamindb#1316]
I want to run a preprocess function on all files in a dataset. is there a "lamin way" of doing this?

e.g. 
```
preprocessor = Preprocess()
v2_dataset = preprocessor(v1_dataset)
``` 

It wasn't very clear from the docs

**Comment by falexwolf** [comment]
Ahhh, everybody seems to have missed this one, sorry!

So, I'd iterate over the files in the dataset via `dataset.files.all()`, something along the following lines:

```
ln.track()  # this will now also work in scripts without passing a Transform
output_files = []
for input_file in input_dataset.files.all():
    output_path = preprocess(input_file.path)
    output_file = ln.File(output_path)
    output_files.append(output_file)
ln.save(output_files)
processed_dataset = ln.Dataset(output_files, name="Preprocessed")  # will link against input_dataset
processed_dataset.save()
```

Of course, this can be wrapped in a pretty class.
