### ISSUE TITLE
Latest nbstripout fails in lamin save

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb#1428]
The latest version (0.7.0) of `nbstripout` fails for all notebooks for me https://github.com/kynan/nbstripout/issues/190
0.6.2 fails for all notebooks written with `nbproject.dev.write_notebook`, because it uses orjson and saves in a bit different format, which is perfectly readable by `jupyter`. `nbstripout` still fails though.

I will pin nbstripout==0.6.1 for now.
We should probably replace `orjson` with a bit slower nbformat.write, but it doesn't help with the latest `nbstripout` anyways.

**Comment by Zethson** [comment]
0.7.1 is supposed to fix this

**Comment by Koncopd** [comment]
Yes, thx, i saw it. I will check when i have time.

**Comment by falexwolf** [comment]
Can we remove the pinning, please?

https://github.com/laminlabs/lamindb/blob/adce9b9c7541cf86a5c517a936c911fcfa22aa6c/pyproject.toml#L52

Also: Let's eliminate orjson entirely -- it's an unnecessary dependency for lamindb.

**Comment by Koncopd** [comment]
Yes, i will do this soon.
