### ISSUE TITLE
postgres API exception when trying to register an already registered instance

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1442]
`lamin init --storage s3://pertpy-datasets --schema bionty`
[...]
`lamin register`

> ❗ instance likely already exists
> ❗ instance likely already exists
> ❗ instance likely already exists
> Traceback (most recent call last):
>   File "/home/zeth/miniconda3/envs/lamindb/bin/lamin", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/lamin_cli/__main__.py", line 126, in register
>     return register_()
>            ^^^^^^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/lamindb_setup/_register_instance.py", line 21, in register
>     init_instance_hub(isettings)
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/lamindb_setup/dev/_hub_core.py", line 112, in init_instance
>     return call_with_fallback_auth(_init_instance, isettings=isettings)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/lamindb_setup/dev/_hub_client.py", line 110, in call_with_fallback_auth
>     raise e
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/lamindb_setup/dev/_hub_client.py", line 106, in call_with_fallback_auth
>     result = callable(**kwargs, client=client)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/lamindb_setup/dev/_hub_core.py", line 149, in _init_instance
>     raise e
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/lamindb_setup/dev/_hub_core.py", line 146, in _init_instance
>     client.table("instance").insert(fields, returning="minimal").execute()
>   File "/home/zeth/miniconda3/envs/lamindb/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 70, in execute
>     raise APIError(r.json())
> postgrest.exceptions.APIError: {'code': '23505', 'details': None, 'hint': None, 'message': 'duplicate key value violates unique constraint "instance_pkey"'}

I expect a single message being like:

"This instance has already been registered. Skipping register" or whatever

**Comment by falexwolf** [comment]
This should not hit any user anymore, in particular given `.register()` will soon be private.
