### ISSUE TITLE
Open to external contributions?

### ISSUE THREAD

**Issue by mukund109** [laminlabs/lamindb#1446]
Hi, I'm interested in contributing to this project and was wondering if you're open to that? If so, any contribution guidelines I should be aware of?

**Comment by sunnyosun** [comment]
You are very welcome to contribute! We don't have a specific guideline yet, but we will certainly add it in the future! 

We use pre-commit and gitmoji, as you see in the repo. 

Other than that, feel free to make PRs and discuss your ideas with us!

**Comment by falexwolf** [comment]
This took ages, but now we have a contributing guide:

- https://github.com/laminlabs/lamindb/pull/1760

I'll close this for now. Let me know if more questions come up, @mukund109!
