### ISSUE TITLE
Migrate to UPath 0.2.0

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb#1503]
https://github.com/fsspec/universal_pathlib?tab=readme-ov-file#migration-guide

**Comment by falexwolf** [comment]
Can we migrate here?

**Comment by Koncopd** [comment]
@falexwolf trying here https://github.com/laminlabs/lamindb-setup/pull/723
got a bug, nothing serious but i would prefer it resolved in upath.

**Comment by Koncopd** [comment]
Yep, it was migrated.
