### ISSUE TITLE
cellxgene-lamin-validator page is not rendering the output

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1523]
https://lamin.ai/docs/cellxgene-lamin-validator

**Comment by Zethson** [comment]
It's being pulled in from the archived repository

**Comment by Zethson** [comment]
That's because they're not rendered upstream in cellxgene-lamin

**Comment by sunnyosun** [comment]
Do you mind briefly debug here: https://github.com/laminlabs/cellxgene-lamin?

**Comment by Zethson** [comment]
Already doing that and I didn't find it yet

Mar 26, 2024 6:22:11 PM Sunny Sun ***@***.***>:
