### ISSUE TITLE
lamindb/_annotate.py:216: error: X | Y syntax for unions requires Python 3.10  [syntax]

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1530]
I get this linting error now. Is this futures compliant and will run on 3.9?

<img width="677" alt="image" src="https://github.com/laminlabs/lamindb/assets/16916678/ea119533-121f-4904-b837-d1a7e1b76b73">

**Comment by falexwolf** [comment]
Fixed: https://github.com/laminlabs/lamindb/commit/71a9269029a927f0d2d2ef87ac510e7640733ba4

But we need a way to prevent this or start to properly use the new union syntax in the OS stack.

**Comment by Zethson** [comment]
Ya, if you `from __future__ import __annotations__` it works fine also when users have Python < 3.10
