### ISSUE TITLE
Final cleanup cell in the intro

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1568]
![image](https://github.com/laminlabs/lamindb/assets/21954664/af5df867-19e4-402e-b635-50a71de332c6)

The final clean up cell has nothing to do with the further influences and is a bit noisy here. I would not show another header. Is there a way to magically make the whole cell not render at all?

**Comment by falexwolf** [comment]
Done: https://github.com/laminlabs/lamindb/commit/2744df75e87efd27e1ee9c7847851b3e624ece91
