### ISSUE TITLE
Notebooks show non-consecutive logging despite being consecutive

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/lamindb#1570]
This notebook is consecutive and it is labeled `is_consecutive=True`.

In my vscode, it looks all good:
<img width="788" alt="Screenshot 2024-04-16 at 16 16 36" src="https://github.com/laminlabs/lamindb/assets/38218185/09a9b912-f09e-40bb-9e97-3806db8dc59c">

But the generated html shows: (https://lamin.ai/laminlabs/lamin-dev/transform/1WyHWxnr4nqu5zKv)
<img width="978" alt="Screenshot 2024-04-16 at 16 14 58" src="https://github.com/laminlabs/lamindb/assets/38218185/aff44179-c0e4-446f-bfd3-d6f61fa62a09">

**Comment by falexwolf** [comment]
@sunnyosun - Can I look at your VS Code? My suspicion is that your VS Code shows a later execution and the report an earlier execution and you had not save the notebook buffer in between. The artifact uids don't match, but unfortunately your time stamps aren't visible in the screenshot from VS Code.
<img width="663" alt="image" src="https://github.com/laminlabs/lamindb/assets/16916678/30399a4f-1766-4f62-b613-a6f6698f9dfb">

**Comment by falexwolf** [comment]
A first round of simplification took place here:

- https://github.com/laminlabs/lamindb/pull/1573

**Comment by falexwolf** [comment]
I think I know how we can do this better.

Instead of relying on the `i_saved_the_notebook` flag, we resort that we used to ascertain that ipylab had actually flushed the buffer.

But now we use it to ascertain that the user flushed the editor buffer to disk within the last 3 seconds before calling `ln.finish()`.

@sunnyosun & @Koncopd, I'll do this, it's very simple & robust logic.

**Comment by Koncopd** [comment]
But ipylab won't work on vs code anyways.

**Comment by falexwolf** [comment]
> But ipylab won't work on vs code anyways.

We'll not use ipylab - by contrast, I'd like us to eliminate it from the dependencies. I fear you misunderstood my suggestion. It's only about comparing timestamps of the on-disk representation and the function call.

**Comment by falexwolf** [comment]
This is the proposed fix:

- https://github.com/laminlabs/lamindb/pull/1581

**Comment by falexwolf** [comment]
I'll close this, it should be fixed in 0.70.2 - let me know if there are more issues.
