### ISSUE TITLE
Unable to save notebook which contains whitespace in the path

### ISSUE THREAD

**Issue by srivarra** [laminlabs/lamindb#1580]
At the end of a notebook, if it's been tracked `ln.finish(i_saved_the_notebook=True)` can error out during the `jupyter nbconvert --to html` step if a path contains whitespace.

<details>
	<summary> Error Output </summary>
	```

		"name": "CalledProcessError",
		"message": "Command 'jupyter nbconvert --to html /Users/srivarra/Davis Lab/NBL/nbl/docs/notebooks/Initialize LaminDB/Clean Clinical Data.ipynb --Application.log_level=40' returned non-zero exit status 255.",
		"stack": "---------------------------------------------------------------------------
	CalledProcessError                        Traceback (most recent call last)
	Cell In[58], line 1
	----> 1 ln.finish(i_saved_the_notebook=True)
	
	File ~/Davis Lab/NBL/nbl/.venv/lib/python3.11/site-packages/lamindb/_finish.py:46, in finish(i_saved_the_notebook)
	     42         logger.error(
	     43             \"Please pass `i_saved_the_notebook=True` to `ln.finish()`, save the notebook, and re-run this cell.\"
	     44         )
	     45         return None
	---> 46     save_run_context_core(
	     47         run=run_context.run,
	     48         transform=run_context.transform,
	     49         filepath=run_context.path,
	     50         finished_at=True,
	     51     )
	     52 else:
	     53     # scripts
	     54     # save_run_context_core was already called during ln.track()
	     55     run_context.run.finished_at = datetime.now(timezone.utc)  # update run time
	
	File ~/Davis Lab/NBL/nbl/.venv/lib/python3.11/site-packages/lamindb/_finish.py:99, in save_run_context_core(run, transform, filepath, transform_family, finished_at)
	     96         return \"aborted-non-consecutive\"
	     97 # convert the notebook file to html
	     98 # log_level is set to 40 to silence the nbconvert logging
	---> 99 subprocess.run(
	    100     \"jupyter nbconvert --to html\"
	    101     f\" {filepath.as_posix()} --Application.log_level=40\",
	    102     shell=True,
	    103     check=True,
	    104 )
	    105 # move the temporary file into the cache dir in case it's accidentally
	    106 # in an existing storage location -> we want to move associated
	    107 # artifacts into default storage and not register them in an existing
	    108 # location
	    109 filepath_html_orig = filepath.with_suffix(\".html\")  # current location
	
	File ~/.rye/py/cpython@3.11.7/install/lib/python3.11/subprocess.py:571, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
	    569     retcode = process.poll()
	    570     if check and retcode:
	--> 571         raise CalledProcessError(retcode, process.args,
	    572                                  output=stdout, stderr=stderr)
	    573 return CompletedProcess(process.args, retcode, stdout, stderr)
	
	CalledProcessError: Command 'jupyter nbconvert --to html /Users/srivarra/Davis Lab/NBL/nbl/docs/notebooks/Initialize LaminDB/Clean Clinical Data.ipynb --Application.log_level=40' returned non-zero exit status 255."
	```
</details>

The error occurs at the following subprocess call.

https://github.com/laminlabs/lamindb/blob/4f8241d45454f585e405685b17d97337c4be89ef/lamindb/_finish.py#L99-L104

If we put quotes around `{filepath.as_posix()}` ->  `\"{filepath.as_posix()}\"` this seems to fix the issue.

As a related issue (or maybe a misunderstanding on my part) when running `ln.track` with a particular transform, I specify the path like below:

```python
transform = ln.Transform(
    name="Clean Clinical Data and add DataFrame", key="Clean Clinical Data", type="notebook", version="0.0.2"
)
transform.save()
ln.track(transform=transform, path=Path(os.getcwd()) / "Clean Clinical Data.ipynb")
```

However I have to set it again manually as well otherwise when running `ln.finish(i_saved_the_notebook=True)` at the end, it's unable to find the notebook.

```python
ln.core.run_context.path = Path(os.getcwd()) / "Clean Clinical Data.ipynb"
```

I wasn't able to figure this one out however.

Thank you!

**Comment by Koncopd** [comment]
Thank you, we will look into it.

**Comment by falexwolf** [comment]
@srivarra - fixed the white space issue here

- https://github.com/laminlabs/lamindb/pull/1581/commits/1a62b3a54c09c6876f685766c6805b94fc2629bd

Darn that you ran into it, we're about to replace the subprocess calls to `jupyter nbconvert` with using the API and you wouldn't have had this issue.

**Comment by falexwolf** [comment]
For this pattern, @srivarra:

```
transform = ln.Transform(
    name="Clean Clinical Data and add DataFrame", key="Clean Clinical Data", type="notebook", version="0.0.2"
)
transform.save()
ln.track(transform=transform, path=Path(os.getcwd()) / "Clean Clinical Data.ipynb")
```

Why are you trying to manually define a `Transform` for your notebook? Simply calling `ln.track()` is enough. Maybe we should consider to let `ln.track(transform=transform)` throw an error if the transform is of type `notebook` or `script`. 😅 

(Defining transforms manually can be needed if you'd like to integrate with workflow managers like Nextflow.)

It'd still be interesting to understand why it fails because, unless your filepath is corrupted, your code looks correct. A traceback would help.

**Comment by srivarra** [comment]
> Why are you trying to manually define a `Transform` for your notebook? Simply calling `ln.track()` is enough. Maybe we should consider to let `ln.track(transform=transform)` throw an error if the transform is of type `notebook` or `script`. 😅

I wanted to set the name and key and saw that this can be done by setting the transform over [here](https://lamin-docs-msjq.netlify.app/docs/project-flow#app-upload-of-phenotypic-data). So, that is definitely not the correct method for notebooks lol, instead for notebooks should I be setting this information like so?
```python
ln.settings.transform.name = "Clean Clinical Data and add DataFrame"
ln.settings.transform.version = "0.0.1"
ln.settings.transform.key = "Clean Clinical Data"
```
Or does `ln.track()` gather the name/key from the title of the notebook?

> It'd still be interesting to understand why it fails because, unless your filepath is corrupted, your code looks correct. A traceback would help.

Here's that traceback:

<details>
	<summary>Traceback</summary>
	
		"name": "TypeError",
		"message": "expected str, bytes or os.PathLike object, not NoneType",
		"stack": "---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	Cell In[37], line 1
	----> 1 ln.finish(i_saved_the_notebook=True)
	
	File ~/Davis Lab/NBL/nbl/.venv/lib/python3.11/site-packages/lamindb/_finish.py:46, in finish(i_saved_the_notebook)
	     42         logger.error(
	     43             \"Please pass `i_saved_the_notebook=True` to `ln.finish()`, save the notebook, and re-run this cell.\"
	     44         )
	     45         return None
	---> 46     save_run_context_core(
	     47         run=run_context.run,
	     48         transform=run_context.transform,
	     49         filepath=run_context.path,
	     50         finished_at=True,
	     51     )
	     52 else:
	     53     # scripts
	     54     # save_run_context_core was already called during ln.track()
	     55     run_context.run.finished_at = datetime.now(timezone.utc)  # update run time
	
	File ~/Davis Lab/NBL/nbl/.venv/lib/python3.11/site-packages/lamindb/_finish.py:87, in save_run_context_core(run, transform, filepath, transform_family, finished_at)
	     83     logger.error(
	     84         \"install nbproject & nbstripout: pip install nbproject nbstripout\"
	     85     )
	     86     return None
	---> 87 notebook_content = read_notebook(filepath)  # type: ignore
	     88 is_consecutive = check_consecutiveness(notebook_content)
	     89 if not is_consecutive:
	
	File ~/Davis Lab/NBL/nbl/.venv/lib/python3.11/site-packages/nbproject/dev/_notebook.py:23, in read_notebook(filepath)
	     17 def read_notebook(filepath: Union[str, Path]) -> Notebook:
	     18     \"\"\"Read a notebook from disk.
	     19 
	     20     Args:
	     21         filepath: A path to the notebook to read.
	     22     \"\"\"
	---> 23     with open(filepath, \"rb\") as f:
	     24         try:
	     25             nb = orjson.loads(f.read())
	
	TypeError: expected str, bytes or os.PathLike object, not NoneType"
</details>

**Comment by falexwolf** [comment]
> Or does ln.track() gather the name/key from the title of the notebook?

Yes, ln.track() gathers everything from your notebook metadata. Please give it a try!

The fix for the white space is out in lamindb 0.70.2.

**Comment by falexwolf** [comment]
> I wanted to set the name and key and saw that this can be done by setting the transform over [here](https://lamin-docs-msjq.netlify.app/docs/project-flow#app-upload-of-phenotypic-data). So, that is definitely not the correct method for notebooks lol, instead for notebooks should I be setting this information like so?

Understood. The `project-flow` code snippets are somewhat artificial as they are meant to illustrate how the lineage across the entire project comes together.

Two actions for us:
- We should carefully review whether we'd actually want to expose all this code user-facing in the way we're doing right now. It likely causes more confusion than clarification. @sunnyosun
-  I will now raise an error if you try to pass a transform for type "notebook" to `ln.track()` - there is a lot of work under the hood so that you don't have to manually provide anything

**Comment by falexwolf** [comment]
To avoid such confusion, I'd from now on raise an error:

- https://github.com/laminlabs/lamindb/pull/1584

**Comment by falexwolf** [comment]
Random note: Your pattern
```
Path(os.cwd())
```
can be simplified to
```
Path.cwd() 
```

**Comment by srivarra** [comment]
@falexwolf 

> > Or does ln.track() gather the name/key from the title of the notebook?
> 
> Yes, ln.track() gathers everything from your notebook metadata. Please give it a try and pay attention to the logging!

Awesome, yup, it does exactly that, thank you!

**Comment by falexwolf** [comment]
Cool! :D

Hence, I'm closing this - feel free to re-open in case there are more issues.
