### ISSUE TITLE
tutorial request: scvi + MappedCollection

### ISSUE THREAD

**Issue by j-bac** [laminlabs/lamindb#1592]
It is not obvious to me how to interface data loaded with `lamindb.core.MappedCollection` into an scvi model. 

For example:
- initializing `adata.X` with `batch['x'] `fails because the matrix is already a `torch.Tensor`
- placing `torch.Tensor`in `adata.layers` is possible but fails to pass the scvi checks

Maybe it is possible by using the `model.train(data_module=data_module) ` parameter ?

```python
import lamindb as ln
import scanpy as sc
import scvi
import scipy
import numpy as np
from torch.utils.data import DataLoader, WeightedRandomSampler

sc.AnnData(np.random.randint(0,10,(500, 10)), obs={'cell_type': np.random.randint(0,5,(500, ))}).write('adata0.h5ad')
sc.AnnData(np.random.randint(0,10,(500, 10)), obs={'cell_type': np.random.randint(0,5,(500, ))}).write('adata1.h5ad')

path_list = ['adata0.h5ad','adata1.h5ad']

mapped_collection = ln.core.MappedCollection(path_list,
    label_keys=['cell_type'],
    encode_labels=['cell_type'],
    join='outer',
    parallel=True
)

sampler = WeightedRandomSampler(
    weights=mapped_collection.get_label_weights("cell_type"), num_samples=len(mapped_collection)
)
dataloader = DataLoader(mapped_collection, batch_size=50, sampler=sampler)


for i,batch in enumerate(dataloader):
    adata = sc.AnnData(scipy.sparse.csr_matrix(batch['x'].shape),
                        layers={'counts':batch['x']},
                        obs={'cell_type':batch['cell_type'],'_storage_idx':batch['_storage_idx']})
    if i == 0:
        scvi.model.SCVI.setup_anndata(adata,layer="counts")
        model = scvi.model.SCVI(adata)
    model.train(adata)
mapped_collection.close()
```

**Comment by Koncopd** [comment]
Hi, @j-bac the problem is that `scvi-tools` doesn't allow to pass external dataloaders in a simple way. I can think on something for this, but might be better to ask `scvi-tools` mantainers for this functionality.

**Comment by j-bac** [comment]
I agree this is more of an scvi problem. I can close this issue if you want and I'll open one on their github

**Comment by Koncopd** [comment]
@j-bac  btw we now have such a tutorial here https://lamin.ai/laminlabs/cellxgene/transform/d1kl7wobCO1H0005
