### ISSUE TITLE
Point bionty docs to their respective guides

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1631]
This https://lamin.ai/docs/pathway
<img width="1488" alt="image" src="https://github.com/laminlabs/lamindb/assets/16916678/a30dcc84-ce13-4213-9493-1f2be1260a6d">

Should be linked from here: 

https://github.com/laminlabs/lnschema-bionty/blob/5807c0225a37119a9ff57966eb91cce24ef4fb24/lnschema_bionty/models.py#L1002-L1014

**Comment by falexwolf** [comment]
This broke the docs, @Zethson 

<img width="1406" alt="image" src="https://github.com/laminlabs/lamindb/assets/16916678/25f2a32f-6af5-44ce-a528-07f2630bf808">

**Comment by Zethson** [comment]
Sorry! Will fix in 20 minutes

**Comment by falexwolf** [comment]
Would be good to build the docs locally if making so many error prone suggestions, or otherwise waiting for the docs build to pass before merging to main (I know that unfortunately we have some flakiness right now, and some runs need to be re-triggered). I urgently need to make a release...

**Comment by falexwolf** [comment]
Thanks! I'll make the release with the broken docs and then re-built production docs with your fix!

**Comment by falexwolf** [comment]
Ran docs locally, getting these warnings:
```
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.CellLine:1: WARNING: unknown document: '/cell_line'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.CellMarker:1: WARNING: unknown document: '/cell_marker'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.CellType:1: WARNING: unknown document: '/cell_type'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.DevelopmentalStage:1: WARNING: unknown document: '/developmental_stage'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.Disease:1: WARNING: unknown document: '/disease'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.Ethnicity:1: WARNING: unknown document: '/ethnicity'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.ExperimentalFactor:1: WARNING: unknown document: '/experimental_factor'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.Gene:1: WARNING: unknown document: '/gene'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.Organism:1: WARNING: unknown document: '/organism'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.Pathway:1: WARNING: unknown document: '/pathway'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.Phenotype:2: WARNING: unknown document: '/phenotype'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.Protein:1: WARNING: unknown document: '/protein'
/Users/falexwolf/repos/laminapp-ui/rest-app/sub/lamindb/sub/lnschema-bionty/lnschema_bionty/models.py:docstring of lnschema_bionty.models.Tissue:1: WARNING: unknown document: '/tissue'
```

**Comment by falexwolf** [comment]
Literally, every modification made to the docs seems invalid. I think it's fair to say that this was haphazardly merged to main across repos and caused more work than it achieved? 🤔

**Comment by Zethson** [comment]
Yes totally. Let's revert it. The CI failed unrelated to this and I took your comment on the PR as approval which I shouldn't have. I'll have a look as soon as I get home.

**Comment by falexwolf** [comment]
And looking at it more closely, I see that there is a simple fix: Adding `docs:` in front of each entity.

```
:doc:`/docs:organism`.
```

**Comment by Zethson** [comment]
Oofff, IDK what to say, sorry

**Comment by falexwolf** [comment]
So, it's super trivial to fix the only issue is that we have this stupidly high number of repositories to propagate this change 😅

**Comment by falexwolf** [comment]
> The CI failed unrelated to this 

Yes, I know, we'll fix the flakiness as soon as we know where it comes from.

> and I took your comment on the PR as approval 

It was a approval but I can't check for link integrity other than running docs locally.

**Comment by falexwolf** [comment]
Wait, I believe the docs build on the `release` branch passes because you didn't bump any version numbers. This makes it much less urgent - fixing tomorrow then is enough!

**Comment by falexwolf** [comment]
Yes, builds on the release branch pass because no bionty release was made. Can wait with fixing the submodule-based builds tomorrow!

Sorry, false alarm!
