### ISSUE TITLE
bio-registries notebook runs too long

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1643]
The bio-registries notebook alone runs 4 min:
```
docs/test_notebooks.py Executing notebooks in /home/runner/work/lamindb/lamindb/docs/bio-registries.ipynb
Scheduled: ['bio-registries']
bio-registries ✓ (279.635s)
Total time: 279.6[35](https://github.com/laminlabs/lamindb/actions/runs/9017775087/job/24777294086?pr=1640#step:15:36)s
``` 

That's too long as an integration test but also for a user when trying something out, isn't it?

**Comment by sunnyosun** [comment]
It's because of this:
<img width="800" alt="Screenshot 2024-05-09 at 16 04 10" src="https://github.com/laminlabs/lamindb/assets/38218185/81621063-f522-478e-952b-12480b5b0ad8">

**Comment by falexwolf** [comment]
Do we need this or can we speed this up somehow?

**Comment by sunnyosun** [comment]
I think this is pretty cool to see what iris lineage looks like, but of course it's fine to remove.

**Comment by falexwolf** [comment]
If it's cool, then let's keep it. Can it be accelerated?

**Comment by sunnyosun** [comment]
The only way to accelerate is to accelerate the logic of adding parents.

**Comment by sunnyosun** [comment]
I moved it into a markdown cell!
