### ISSUE TITLE
⬆️ python 3.12 not compatible

### ISSUE THREAD

**Issue by michael-swift** [laminlabs/lamindb#1647]
I find using 3.12 results in similar behavior to this: 

https://discuss.dagster.io/t/16372898/anyone-else-run-into-importerror-cannot-import-name-posixfla

and can be resolved by downgrading to 3.11. I might be missing something but I don't see an explicit requirement of Python < 3.12

**Comment by Koncopd** [comment]
Thank you for reporting. This will be resolved when we upgrade `upath`.

**Comment by Koncopd** [comment]
Should be fine now, please reopen if you still have problems.
