### ISSUE TITLE
♻️ Eliminate hitting `laminlabs/cellxgene` in unit tests

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1659]
This is bad because
1. it's by far the slowest components of the unit tests
2. it keeps breaking during migrations
3. we simply shouldn't hit a production instance during unit tests

The screenshot is for the first bullet - waiting for test_transfer.py to pass:
<img width="1689" alt="image" src="https://github.com/laminlabs/lamindb/assets/16916678/da43aaa9-8722-4287-8de3-342466c6db17">

**Comment by sunnyosun** [comment]
Shall we switch to using lamin-dev?

**Comment by falexwolf** [comment]
That's better because we can more rapidly migrate it, but also that's a production instance that shouldn't be migrated for testing purposes. Can't we make a local test instance during test start-up as a fixture? 🤔 Or if this doesn't currently work because we can't load multiple instances in the session as a call from the noxfile?

**Comment by falexwolf** [comment]
This is duplicated with the old issue reference above.
