### ISSUE TITLE
🐛 cpu_affinity not available on Mac

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1664]
```
>               n_workers = len(psutil.Process().cpu_affinity())
E               AttributeError: 'Process' object has no attribute 'cpu_affinity'
```

**Comment by Koncopd** [comment]
Interesting, i thought `psutil` is cross-platform.

**Comment by Koncopd** [comment]
https://github.com/giampaolo/psutil/blob/3c518a384dda6dd11223499fc26b5bacf08bb8d5/psutil/__init__.py#L852
uh, sorry, fixing

**Comment by falexwolf** [comment]
I'm fixing like so:

```
try:
    n_workers = len(psutil.Process().cpu_affinity())
except AttributeError:
    # Fallback method
    n_workers = os.cpu_count()
```

**Comment by falexwolf** [comment]
No need for you to fix!

**Comment by Koncopd** [comment]
No, this is incorrect unfortunately.

**Comment by Koncopd** [comment]
Could you quckly check if `len(os.sched_getaffinity(0))` is available on mac?

**Comment by Koncopd** [comment]
ok, i see that it is not available for mac.

@falexwolf 
i think it is better to do
```
try:
    n_workers = len(psutil.Process().cpu_affinity())
except AttributeError:
    # Fallback method
    n_workers = psutil.cpu_count()
```

**Comment by Koncopd** [comment]
But this is pretty strange that there is just no way to detect the number of cpus available to a process on mac.

**Comment by falexwolf** [comment]
Done that!
