### ISSUE TITLE
📝 Consistently use `ln.Annotate` for any anndata- and df-like artifact

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1682]
We have several examples that rely on the lower-level API that's now private:

https://github.com/laminlabs/lamin-usecases/pull/129

**Comment by falexwolf** [comment]
@sunnyosun - does this make sense to bump up the prio list?

**Comment by sunnyosun** [comment]
https://github.com/laminlabs/lamin-usecases/commit/862b690d7a7a3113ea1d8db9f6ae336091811eac

**Comment by falexwolf** [comment]
Thank you! 🙏
