### ISSUE TITLE
🐛 `.get()` doesn't work with `using`

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/lamindb#1718]
<img width="828" alt="Screenshot 2024-07-04 at 11 19 37" src="https://github.com/laminlabs/lamindb/assets/38218185/7b3e634b-4f88-4d5a-976b-8fa6df9d8b0a">

**Comment by Koncopd** [comment]
Hi, `.using` returns `django` `QuerySet`. For `QuerySet.get`  the correct way is to specify a field https://docs.djangoproject.com/en/5.0/topics/db/queries/#retrieving-a-single-object-with-get
![image](https://github.com/laminlabs/lamindb/assets/3065736/a58b07da-5346-4bd4-a6fd-3226b18ab0ae)
But when you call `ln.Artifact.get` you actually call `Registry.get` implemented here https://github.com/laminlabs/lnschema-core/blob/e306c6b755709307c36e97771e0fc7ca92816556/lnschema_core/models.py#L597
This is the cause of the difference.
I agree this is confusing, maybe we need to make this uniform.

**Comment by Koncopd** [comment]
@falexwolf do you think we should change `Registry.get`?

**Comment by falexwolf** [comment]
Yes, we need to homogenize this. Hm. 🤔 

I think we can subclass `QuerySet.get()` to enable the arg call that we want. That'd be a clean solution that will work for Lamin and Django users.

**Comment by falexwolf** [comment]
Fixed here:

- https://github.com/laminlabs/lamindb/pull/1829
