### ISSUE TITLE
Consider unit tests for save_vitessce_config

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1731]
It says that it's currently tested in https://github.com/laminlabs/lamin-spatial but even there, it's only notebooks.

**Comment by falexwolf** [comment]
It's "unit-tested" here: https://github.com/laminlabs/lamindb/blob/main/docs/storage/vitessce.ipynb
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/60854a6b-8ce0-4acf-891b-bf5ea9d61b2f">

Running these from within a script is possible but the main goal is to actually hit S3. We could convert this into a pytest script when we have unit tests in the storage group where this problem holds for a few other cases.
