### ISSUE TITLE
reference target not found: lamindb.core.Registry.filter -> filter method references not working

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1739]
Suddenly running into this here: https://github.com/laminlabs/lamindb/actions/runs/9971389106/job/27553149037?pr=1738

It does indeed not render properly: https://docs.lamin.ai/lamindb.core.querymanager#lamindb.core.QueryManager.search

I am not sure what's causing this though because it works for `lookup`. Both, `lookup` and `filter` are a part of the `RegistryMeta` class of `Registry` in lnschema-core. `Registry` is imported in `lamindb.core`.

:thinking:

**Comment by Zethson** [comment]
```
>>> ln.core.Registry.filter
<bound method RegistryMeta.filter of <class 'lnschema_core.models.Registry'>>
```

It's there...

**Comment by Zethson** [comment]
So that's the difference:
```
>>> ln.core.Registry.filter
<bound method RegistryMeta.filter of <class 'lnschema_core.models.Registry'>>
>>> ln.core.Registry.lookup
<bound method lookup of <class 'lnschema_core.models.Registry'>>
```

**Comment by falexwolf** [comment]
It's going to be resolved with this refactor:

- https://github.com/laminlabs/lamindb/pull/1740

**Comment by falexwolf** [comment]
As you figured, the issue is the different way of defining these methods. I'm homogenizing it in the refactor.

It only affects the docs, the API works as expected.

I'm unclear why this didn't hit in the initial buils.

**Comment by Zethson** [comment]
I assume that's fixed now with your PR. The docs build also ran through.

**Comment by falexwolf** [comment]
Yes, it's all fixed now.
