### ISSUE TITLE
search searches for substrings in uid

### ISSUE THREAD

**Issue by insavchuk** [laminlabs/lamindb#1758]
<img width="1171" alt="Screenshot 2024-07-27 at 16 58 00" src="https://github.com/user-attachments/assets/0b7d4084-3a68-4011-aefc-7d487de1070a">

At ingestion time, the search function checks across all fields including "uid", where it finds the substring "tox". However, the cell marker is saved based on its name ("Tox"), which we can expect has nothing to do with the uid. I suggest that warning be adjusted to be uid-agnostic, probably by modifying the way search is done on records at the ingestion step.

**Comment by Zethson** [comment]
Makes a lot of sense, thank you!

**Comment by Zethson** [comment]
I do see your error, but I cannot reproduce it and I think that actually already search only for name:

```python
import bionty as bt
cm_1 = bt.CellMarker(name="cm1").save()
bt.CellMarker(name=cm_1.uid).save()
```

results in

![image](https://github.com/user-attachments/assets/fa7c29ef-98f6-4b95-bc95-4518c4c399f9)

which does not trigger what you saw earlier. I am not sure what happened in your case. Does this record have a synonym?

**Comment by insavchuk** [comment]
Hi Lukas, just tried running this: 

```
import bionty as bt
bt.CellMarker.search("Tox")
```

and got back:

`<QuerySet [CellMarker(uid='4k1OgVoPi9DC', name='Tox', created_by_id=6, organism_id=1, updated_at='2024-07-27 15:53:11 UTC'), CellMarker(uid='5GtoxNrVa5wj', name='CD31', synonyms='', gene_symbol='PECAM1', ncbi_gene_id='5175', uniprotkb_id='A0A075B738', created_by_id=6, organism_id=1, source_id=18, updated_at='2024-07-01 07:08:45 UTC')]>`

So it doesn't look like there is anything related to the string combination "Tox" in the record for the CD31 marker except for the "tox" substring in the uid. I also tried a search for "toxNrV" and it returns just the record for CD31.

**Comment by falexwolf** [comment]
It did search _all_ fields for some time until 3 weeks ago... I fixed it here: https://github.com/laminlabs/lamindb/commit/772da64b46705cf31f615dc4f6d94a486ceeb273
