### ISSUE TITLE
Missleading "create new record via" message

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1776]
> ❗ 1 term (100.00%) is not validated for symbol: ENSG00000282080
>    couldn't validate 1 term: 'ENSG00000282080'
> →  if you are sure, create new record via ln.Gene() and save to your registry

Ideally, it's `bt` but it might not be easy to decipher the schema (and how it was imported/aliased to) for a good suggestion. Nevertheless, this is wrong and misleading.

**Comment by sunnyosun** [comment]
Could you simply remove `ln.`?
