### ISSUE TITLE
🎨 Why is `list_source` called this way and not `.sources` or similar?

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1863]
It looks like it returns a `QuerySet` and not a list.

<img width="441" alt="image" src="https://github.com/user-attachments/assets/f30e5537-5410-4203-9fb5-ae79e0dc357d">

**Comment by falexwolf** [comment]
So, the above could simply make use of the pattern that we'd encourage, rather than requiring users to learn a new pattern: 

```
bt.CellType.sources.get(currently_used=True)
```

**Comment by sunnyosun** [comment]
It needs to be `.sources()`

**Comment by sunnyosun** [comment]
https://github.com/laminlabs/bionty/pull/116

**Comment by sunnyosun** [comment]
@falexwolf can you confirm you want this?

**Comment by falexwolf** [comment]
Hm. I don't get the reason why this isn't a `ManyToMany` accessor. Why isn't it?

We should have a naming scheme for such cases that behave like a ManyToMany but actually aren't. 

How about `query_sources()`? But I gotta admit that any naming scheme seems odd if `.sources` can't be a many to many.

**Comment by sunnyosun** [comment]
Because it's not a relationship! Look at the schema, the relationship is a FK for each record called `.source`.

`.sources()` is a method in the base class.

**Comment by sunnyosun** [comment]
It's at the class level!

**Comment by falexwolf** [comment]
Why don't we recommend the following?

```
bt.Source.filter(created_cell_types__isnull=False).all()
```

This is 100% equivalent to getting all the users who, e.g., created artifacts. We should have a single way for users to query this inverse relationships. The easiest would be to rely on existing Django idioms for that matter, I'd say. 🤔 

Unfortunately, we might just have removed the easy way to query for all `Source` records. This Slack [thread](https://laminlabs.slack.com/archives/C046F63LJJ2/p1725833297001919).

**Comment by sunnyosun** [comment]
The inverse relationship is removed.

**Comment by sunnyosun** [comment]
```bt.Source.filter(created_cell_types__isnull=False).all()```
This is to query for which sources are linked to the existing records.

`.list_source()` is getting available sources independent of what ontology records are in the registry!

Even if `bt.CellType` is empty, `bt.CellType.list_sources()` will return all sources!

**Comment by falexwolf** [comment]
> is getting available sources independent of what ontology records are in the registry

But that's even easier to achieve with

```
bt.Source.filter(entity="CellType").all()
```

I don't understand why we don't clearly document that query and rather introduce something non-idiomatic.

This is already a long list for which it's hard to develop intuition for:
<img width="211" alt="image" src="https://github.com/user-attachments/assets/88a52a7c-aa46-4f23-8c36-7ef26504c7d3">

**Comment by sunnyosun** [comment]
OK, we can remove it

**Comment by falexwolf** [comment]
This broke the usecases. Can you quickly fix them, @sunnyosun?
