### ISSUE TITLE
If the title changes, the Transform should change as well

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1923]
### Report

Didn't really work in the demo.

When a user changed the notebook title, running `ln.context.track()` doesn't detect the change.

### Version information

NA

**Comment by falexwolf** [comment]
This has always been tested and I'm not aware that it was ever broken. It's also working right now:

<img width="790" alt="image" src="https://github.com/user-attachments/assets/4bc0c025-6c32-4d91-a6f0-d763bc8d4f4f">

Tentatively closing. Let's chat about what gave you the impression it wasn't working!
