### ISSUE TITLE
📝 Document `LAMIN_CACHE_DIR` and `LAMIN_SETTINGS_DIR`

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1961]
Should be in https://docs.lamin.ai/setup

Background: [here](https://laminlabs.slack.com/archives/C04FPE8V01W/p1727103905348019?thread_ts=1727103004.497639&cid=C04FPE8V01W)

**Comment by Koncopd** [comment]
Where should the description go?

**Comment by falexwolf** [comment]
In a meaningful place on https://docs.lamin.ai/setup :)

It's a setup step. You can explain that there are two directories that Lamin uses to store settings and cached data and that these default to HOME and whatever APPDIRS suggests. In cases where it needs to be configured, these two env variables would need to be set (it'd be nice if it was a single env variable, TBH). Maybe we can store settings in the cache dir, too...

**Comment by Koncopd** [comment]
ok, got it.
btw appdirs seems to be deprecated https://github.com/ActiveState/appdirs
maybe we should move to https://github.com/tox-dev/platformdirs ?
