### ISSUE TITLE
🐛 New gotrue release (`2.9.0`) breaks auth, please pin `2.8.1`

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#1995]
It's going to be pinned as of the next lamindb release (`0.76.10`) scheduled for today.

Background: https://pypi.org/project/gotrue/#history

**Comment by Koncopd** [comment]
Adds upper bound here https://github.com/laminlabs/lamindb-setup/commit/0bcc2f7195ff9432bd40ffd9e17069b314bfc42f
