### ISSUE TITLE
🐛 Cannot store parameters that are very large dictionaries

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#2004]
Internal Slack thread: https://laminlabs.slack.com/archives/C07DB677JF6/p1727704769858209

**Comment by falexwolf** [comment]
I investigated and have a solution: https://lamin.ai/laminlabs/lamindata/transform/jgTrkoeuxAfs0000

But the solution requires a migration so I need to ponder a bit on whether it'd be breaking or not.

**Comment by falexwolf** [comment]
After analyzing more, I'm pretty convinced that we should not hash these dicts just to make the unique constraint for `param` and `value` work.

Hence, I'll simply create a non-breaking migration that removes this constraint.

Here is the analysis: https://lamin.ai/laminlabs/lamindata/transform/jgTrkoeuxAfs0001

**Comment by falexwolf** [comment]
Problem is resolved: https://lamin.ai/laminlabs/lamindata/transform/jgTrkoeuxAfs0002

<img width="401" alt="image" src="https://github.com/user-attachments/assets/694025c0-0cec-433f-9c92-421ff04d43ee">

Via: https://github.com/laminlabs/lnschema-core/pull/441

**Comment by falexwolf** [comment]
PS: The migration is non-breaking so can without trouble be applied off-cycle.

**Comment by falexwolf** [comment]
Propagated to lamindb main:

- https://github.com/laminlabs/lamindb/pull/2018

**Comment by falexwolf** [comment]
PPS: As expected, everything continues to work perfectly fine without any `(param, value)` duplications: https://lamin.ai/laminlabs/lamindata/transform/jgTrkoeuxAfs0003
