### ISSUE TITLE
Native support for default values in Curator

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#2027]
### Description of feature

At the hackathon I'm writing a few custom Curators and pretty much always I want to support default values. So far we always implemented something like:

```
def _add_defaults(data: pd.DataFrame, defaults: dict[str, str] = None):
    if defaults:
        for col, default in defaults.items():
            if col not in data.columns:
                data[col] = default
            else:
                data[col].fillna(default, inplace=True)
```

This function is then called in the constructor of the subclass.
I wonder whether we can or should even support a generalized version of this in `ln.Curator` directly.

**Comment by sunnyosun** [comment]
My opinion in general is that any operations that modify input data should be user-specific logic. Such as subsetting, removing/filling NAs, and adding defaults.

Also adding defaults during init slows things down, as we also need to validate the default values. 

So I don't think we should support this.

**Comment by Zethson** [comment]
Yeah I see that. We don't want to start with `inplace` and `copy` parameters either. 

> Also adding defaults during init slows things down, as we also need to validate the default values.

Yeah but if one does that later it also slows the process down so it doesn't matter.

I'm still in favor but closing this for now. If other people raise this issue again, we can revisit it.
