### ISSUE TITLE
🚸 Indenting and relevance

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#2071]
Source: https://docs.lamin.ai/scrna2

The indenting is off here:

<img width="755" alt="image" src="https://github.com/user-attachments/assets/8bf0e586-158f-46f2-a2e4-e2a8208573b8">

Also: evidently the block does not proceed with what's recommended. Is the hint relevant?

**Comment by Zethson** [comment]
I don't think that for the purpose of this tutorial the gene hint is helpful. It's more distracting although it can be relevant in some cases. Maybe it wasn't there with an older ensembl version? Anyways, could we remove those genes from the dataset?

**Comment by falexwolf** [comment]
Or say "consider adding these genes" instead of "please add those genes" which seems like one should do it (even though the tutorial doesn't do it)

**Comment by sunnyosun** [comment]
What's missing in this tutorial is simply a `curator.validate()` call in this block:

<img width="828" alt="Screenshot 2024-11-05 at 11 54 03" src="https://github.com/user-attachments/assets/c3bca5e7-7b57-4e12-8414-c207a1564c39">
