### ISSUE TITLE
🚸 Enabling to append to a collection

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#2073]
This here is horrible UX, both in terms of how the constructor is called and in terms of the logging.

<img width="588" alt="image" src="https://github.com/user-attachments/assets/5530623e-21c5-4f0d-86db-2c366064bb1a">

What we want instead is:

```python
collection_v2 = collection_v1.append(artifact)
```

**Comment by Koncopd** [comment]
done here https://github.com/laminlabs/lamindb/pull/2077
