### ISSUE TITLE
`add_validated_from_var_index` is suggested but it doesn't even exist anymore

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#2108]
### Report

```
• mapping var_index on Gene.ensembl_gene_id
!    found 2 validated terms: 'ENSG00000255823', 'ENSG00000272370'
→ save terms via .add_validated_from_var_index()
```

AttributeError: 'Curator' object has no attribute 'add_validated_from_var_index'.

See https://github.com/search?q=repo%3Alaminlabs%2Flamindb+add_validated_from_var_index&type=code

It got removed recently.

**Comment by sunnyosun** [comment]
Could you provide a mini input df to reproduce this?

**Comment by Zethson** [comment]
Not there anymore. Not sure what I did back then.
