### ISSUE TITLE
source schema has additional modules: {'findrefs'}

### ISSUE THREAD

**Issue by jkobject** [laminlabs/lamindb#2187]
### Usage question

I get this when running l`n.Collection.using(instance="laminlabs/cellxgene").filter(name="cellxgene-census", version='2024-07-01').one()` any reasons why?

**Comment by Zethson** [comment]
Hi @jkobject 

we are currently in the process of adding more in-depth references to the `laminlabs/cellxgene` instance using the https://docs.lamin.ai/findrefs schema. Therefore, it is now required to also have `findreferences` installed. Please install it via `pip install findrefs`. I will adapt the instructions of all guides today.

I'm sorry for the inconvenience! Please let me know if this does not resolve your issue.
