### ISSUE TITLE
hf warning

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#2192]
We get this warning on main now:

<img width="667" alt="image" src="https://github.com/user-attachments/assets/d871f673-afd8-45a4-bcaf-7aec2b3b0d7a">

**Comment by falexwolf** [comment]
@Koncopd, this is something to fix before the release, please. I guess it's quick.

**Comment by Koncopd** [comment]
I don't understand, does it have anything with huggingface?

**Comment by Koncopd** [comment]
@falexwolf i need more info

**Comment by Koncopd** [comment]
ok, i can reproduce with a normal notebook, checking.

**Comment by Koncopd** [comment]
ok, i see, this happens when on artifact init, when it checks if the provided path is a child of huggingface storage path (registered in lamindata) https://github.com/laminlabs/lamindb/blob/8a3e91bc2a358c5519bb9524b4981f7b6bb95ba8/lamindb/_artifact.py#L105

**Comment by Koncopd** [comment]
Fixed here https://github.com/laminlabs/lamindb-setup/pull/902
