### ISSUE TITLE
Sorting a table by last_modified rows: initializing `updated_at` as `None` vs. as `created_at`

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#222]
Option A: Init `updated_at` as None/null
Option B: Init `updated_at` as `created_at`

In A, to sort by "last modified", we sort columns by `created_at` if `updated_at` is None, and otherwise by `updated_at` and then zip both search results.

That's equivalent to sorting by `updated_at` if initializing `updated_at` with `created_at` (which was the original implementation).

**Comment by falexwolf** [comment]
One note: Coalesce on columns from two tables seems to be slow for VARCHAR but not for TEXT in POSTGRES: https://dba.stackexchange.com/questions/297483/why-does-coalesce-prevent-the-use-of-an-index-on-a-varchar-but-not-on-a-text-co

**Comment by falexwolf** [comment]
Overall, there seems to be no reason benchmarking-related reason to choose option B over A: https://lamin.ai/docs/lndb-scale/examples/2022-09-28-timestamps

I'd hence suggest going with option A, given its pros.

**Comment by fredericenard** [comment]
Ok, let's choose option A :)

**Comment by falexwolf** [comment]
🙏 

Let's see when we regret it. 😆
