### ISSUE TITLE
💄 Create a more intuitive `artifact.describe()`

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#2221]
@chaichontat proposed the below in early February:

![image](https://github.com/user-attachments/assets/20d242bb-6285-48dc-99b2-1c5415af008a)

Internal [Slack ref](https://laminlabs.slack.com/archives/C04FPE8V01W/p1708550712303329?thread_ts=1708478206.235429&cid=C04FPE8V01W).

More internal Slack refs on this topic:

- https://laminlabs.slack.com/archives/C04FPE8V01W/p1729856432777079

**Comment by falexwolf** [comment]
Here is a first draft building on @chaichontat's proposal: https://lamin.ai/laminlabs/lamindata/transform/A4EupIQ7dEWx0000

**Comment by falexwolf** [comment]
This is better:
<img width="741" alt="image" src="https://github.com/user-attachments/assets/20fb93ca-5454-452c-a318-dbaecfc4bb48">

<details><summary>Code</summary>
<p>
from rich.tree import Tree
from rich.text import Text
from rich.table import Table, Column

def highlight_time(iso: str):
    tz = datetime.datetime.now().astimezone().tzinfo
    res = (
        datetime.datetime.fromisoformat(iso)
        .replace(tzinfo=datetime.timezone.utc)
        .astimezone(tz)
        .strftime("%Y-%m-%d %H:%M:%S")
    )
    return Text(res, style="dim")

# Define consistent column widths
NAME_WIDTH = 25
TYPE_WIDTH = 25
VALUES_WIDTH = 40

# Main artifact tree
artifact = Tree(Text("Artifact – h5ad", style="bold"), guide_style="dim")

general = artifact.add(Text("General", style="bold green"))
general.add(".uid = 'dP0F1fEQWtorhDaI0000'")
general.add(".storage = s3://...")
general.add(Text.assemble(".path = ", ("storage/", "dim"), " example_datasets/dataset2.h5ad"))
general.add(Text.assemble(".created_at = ", highlight_time("2024-11-25 14:59:38")))
general.add(Text(".transform = 'Towards pretty dataframes with features & params'", style="green"))

# Labels as a branch of artifact
labels = artifact.add(Text("Labels", style="bold red"))
labels_table = Table(
    Column("Name", style="", no_wrap=True, width=NAME_WIDTH),
    Column("Type", style="dim", no_wrap=True, width=TYPE_WIDTH),
    Column("Values", width=VALUES_WIDTH, no_wrap=True),
    show_header=False,
    box=None,
    pad_edge=False,
)
labels_table.add_row(".cell_types", Text("bio.CellType", style="dim"), "T cell, B cell")
labels_table.add_row(".ulabels", Text("ULabel", style="dim"), "DMSO, IFNG, Candidate marker study 2")
labels.add(labels_table)

# Features as a branch of artifact
features = artifact.add(Text("Features", style="dark_orange bold"))

# Create combined tables for each feature group that include the header
def create_feature_table(name: str, type_info: str, data: list) -> Table:
    table = Table(
        Column(Text.assemble((name, "purple"), (" ← " + type_info, "dim")), style="", no_wrap=True, width=NAME_WIDTH),
        Column("", style="dim", no_wrap=True, width=TYPE_WIDTH),
        Column("", width=VALUES_WIDTH, no_wrap=True),
        show_header=True,
        box=None,
        pad_edge=False,
    )
    for row in data:
        table.add_row(*row)
    return table

# External features
external_data = [
    ("study", Text("cat[ULabel]", style="dim"), "Candidate marker study 2"),
    ("duration_s", Text("float", style="dim"), "122.0"),
    ("temperature", Text("float", style="dim"), "22.6"),
]
features.add(create_feature_table("external", "3", external_data))

# Obs features
obs_data = [
    ("cell_type_by_model", Text("cat[bionty.CellType]", style="dim"), "B cell, T cell"),
    ("perturbation", Text("cat[ULabel]", style="dim"), "DMSO, IFNG"),
]
features.add(create_feature_table("obs", "2", obs_data))

# Var features 
var_data = [
    ("CD38", Text("number", style="dim"), ""),
    ("CD4", Text("number", style="dim"), ""),
    ("CD8A", Text("number", style="dim"), ""),
]
features.add(create_feature_table("var", "3 [bionty.Gene]", var_data))

# Print the complete tree
from rich import print
print(artifact)


</p>
</details>

**Comment by Zethson** [comment]
Be careful with so many colors. They can render pretty differently on different terminals. The brighter or darker they are, the higher the risk that they will be unreadable. The dark red that I see here is risky IMO.

Generally, the biggest win for me would be https://laminlabs.slack.com/archives/C04FPE8V01W/p1729856432777079 because even now, I think that the output is nothing but confusing. Especially to people that are new to lamin.

**Comment by falexwolf** [comment]
> I'm not sure. The name datasets is a bit weird because that's the whole Artifact. data would be more correct maybe?

That's an interesting take and I'm surprised to see us misaligned on such a fundamental topic! To me, the dataset/artifact is the data on S3. The artifact object in LaminDB is a wrapper around it that contextualizes the metadata of that dataset/artifact. So, an artifact object in lamindb is **not** the artifact, it's just a wrapper.

Of course in casual language you wouldn't make that difference, but it's important that we use the same finegrained definitions.

The problem with the term `data` is that it's too overloaded. Both the metadata and the data in the dataset are adata. In fact, the dataset contains numeral actual data and metadata in terms of identifiers.

**Comment by falexwolf** [comment]
Can you take this @sunnyosun? First thing would be to refactor all data gathering logic and separate it from the "printing logic". I already did this for the whole features part in my last PR with Claude's help:

- https://github.com/laminlabs/lamindb/pull/2218

It'll be easy for the "labels" part.
