### ISSUE TITLE
unneeded new line in ln.track

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb#2224]
### Add a description

![image](https://github.com/user-attachments/assets/93dde95d-555e-4c31-b0d8-3b348a969181)

**Comment by falexwolf** [comment]
I'm pretty sure there is no new line, I've watched out for it:

<img width="487" alt="image" src="https://github.com/user-attachments/assets/bfb8ce70-25d7-407a-9109-4ebe6fd7482b" />

<img width="416" alt="image" src="https://github.com/user-attachments/assets/bc5fc63a-3a90-407d-a686-84593d12ff82" />
