### ISSUE TITLE
🐛 `ln.finish` shows RStudio message

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb#2257]
### Add a description

got this one https://github.com/laminlabs/lamindb/blob/11fb8a4ee3615a522fc2c802adc2271b11e49cb5/lamindb/_finish.py#L22 on ln.finish for some reason on sagemaker.

**Comment by Koncopd** [comment]
No, maybe i am not right, can't reproduce this.

**Comment by falexwolf** [comment]
Let's keep this open. Sunny also managed to produce this once. I still don't understand how it's possible though because for Python another `NotebookNotSaved` error should fire earlier.

**Comment by Koncopd** [comment]
I see it again
![image](https://github.com/user-attachments/assets/d2241bf4-72bf-49cb-894f-fe7a65b189e0)
