### ISSUE TITLE
Enhancement issue template no longer autolabels the issue

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#2264]
### Add a description

https://laminlabs.slack.com/archives/C04A88BKZPX/p1733323496635319?thread_ts=1725551865.885799&cid=C04A88BKZPX

**Comment by Zethson** [comment]
@falexwolf is that by design because you also want `UX` here or?

**Comment by falexwolf** [comment]
It had a "bug" label before. But I'd reserve the "bug" label for the "Bug" issue. Which label would you put here? It depends on the type of enhancement (features vs. ux etc.), doesn't it?

**Comment by Zethson** [comment]
No, it had the sparkles emoji label before: https://github.com/laminlabs/lamindb/blob/39e0f529a41d9cbc475e52fe3aa0b8095af21494/.github/ISSUE_TEMPLATE/feature_request.yml

I'd have autolabeled these with that and then if necessary one can add an additional UX label. But it's not a big deal.
