### ISSUE TITLE
🐛 `Curator.from_tiledbsoma()` omits simple feature dtypes in the dataset

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#2285]
As evident from the screenshots below, the `sample_note` feature is not validated & linked.

https://lamin.ai/laminlabs/lamindata/transform/08sjdejxVP2Q0004

Compare:

<img width="921" alt="image" src="https://github.com/user-attachments/assets/ae1376b4-af3e-4602-9491-0d42a5cadeb6" />

To:

<img width="922" alt="image" src="https://github.com/user-attachments/assets/20fac6d8-7b5a-418e-ae7d-a158e0b61897" />

It's unfortunate that I somehow didn't notice that there was no test for this case.

**Comment by Koncopd** [comment]
It registers only the features passed to `categoricals`.

**Comment by falexwolf** [comment]
I see this logic:

https://github.com/laminlabs/lamindb/blob/2a1709990b5736b480c6de49c0ada47fafc8b18d/lamindb/_curate.py#L1538-L1543

> It registers only the features passed to categoricals.

That's inconsistent with other curators.

**Comment by Koncopd** [comment]
please try replacing `values=list(self._obs_fields.keys())` with `values=self._valid_obs_keys`
