### ISSUE TITLE
🚸 Shall we make `aws` and `ourprojects` default dependencies?

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#2301]
Goal is to cut down the optionality/complexity of installation.

While purely local usage or purely GCP wouldn't need it, it seems that these are edge cases. Almost anybody will at some point want to pull something from an S3 bucket. Hence I vote to remove the `aws` extra and add the dependencies to the defaults.

For `ourprojects`, it also seems that we shouldn't require an extra but simply install it. It has no additional dependencies at all and is just a few 100 lines of Python code.

`bionty` & `jupyter` indeed bring some additional dependencies; hence these merit extras.

@Zethson @sunnyosun @Koncopd

**Comment by falexwolf** [comment]
This is how this looks:

- https://github.com/laminlabs/lamindb/pull/2302

**Comment by Zethson** [comment]
`aws` I can see but I think @Koncopd knows better whether there'll be any potential conflicts in existing environment. TBH I was sometimes surprised at how many issues dependencies like boto3 caused.

Concerning `ourprojects` - generally also yes as long as we pin it like you're doing.
