### ISSUE TITLE
Do we really really really need the composite primary key that specifies a version?

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#239]
Currently, we have this layout for `dobject` with a composite primary key (and a few selected other tables where we think we have a clear idea of what "versioning the entity" means):

**dobject**

id (PK) | v (PK) | name (str) | dtransform_id (FK transform) | created_at | updated_at
--- | --- | --- | --- | --- | ---
ie3j | 1 | datasetA | 398fj | 2022-09-28 | null
ie3j | 2| dataset v2 | 379fh |  2022-09-29 | null

I've previously consulted on this with a number of people, including experienced data system builders. And the response was: yes, this seems the only way to enable data versioning in the sense: "enable a simple query for multiple versions of the same dobject=dataset" (above, `dobject_id == ie3j`). Now, I'm less sure.

While I still think we want the ability to version rows in tables, for many entities, this might in fact be a very rare case. For `dobject`, this will be a very rare case if most of the table is populated through automatized pipelines that only error rarely.

The amount of complexity introduced by a composite primary key is substantial in particular in a schema that references `dobject` from many tables.

So, how can we enable queryability of multiple versions of the same thing in the rare cases we need it, without introducing a composite primary key with `(id, v)`?

The meaning of "a different version of the same thing" typically means relating a thing to its original version. Like, a re-processed dataset to its original version, or a refactored notebook/software to its original version, etc. In such cases, one wants to have a simple label of referencing the new version vs. the old version, like a semver version number (0.2.0 vs. 0.1.0).

Let's look at the `dobject` case again and see whether we can achieve this with a `multiversion` column that references a `dobject_multiversion` table:

**dobject**

id (PK) | name (str) | multiversion (FK dobject_multiversion) | dtransform_id (FK dtransform) | created_at | updated_at 
--- | --- | --- | --- | --- | ---
ie3j | dataset A | IUDF | 398fj | 2022-09-28 | null
cp39 | dataset A v2 | IUDF | 379fh | 2022-09-29 | null

**dobject_multiversion**

id (PK) | 
--- | 
IUDF |

**Comment by falexwolf** [comment]
If we'd adopted a new version along the lines of the suggestion of the above, the ingestion logic would need to change as follows:

```
db.ingest(new_dataset, version=original_dataset)
# in the background, this will populate the `multiversion` column
```

**Comment by falexwolf** [comment]
An alternative to the above would be using the ID of the original dobject in the "multi-version family of the same dobject":

**dobject**

id (PK) | name (str) | multiversion (FK dobject) | dtransform_id (FK dtransform) | created_at | updated_at 
--- | --- | --- | --- | --- | ---
ie3j | dataset A | ie3j | 398fj | 2022-09-28 | null
cp39 | dataset A v2 | ie3j | 379fh | 2022-09-29 | null

**Comment by falexwolf** [comment]
Or, as @sunnyosun suggests, maybe we should consider completely dropping any versioning from the `dobject` table.

In fact,in possibly most (all?) use cases of versioning (1: re-running a different pipeline on the same input, 2: re-doing an analysis on the same input, etc.), there are conserved & differing metadata fields that enable to query for multiple versions of the same thing.

Say, in use case 1, one has an idea of a dataset that belongs to certain metadata conditions that one queries for (data type, biological system, etc.). Upon re-running the pipeline on the same source data, one obtains two query results for this metadata condition. The different versions of this dataset are then labeled by the different pipeline versions (and one can even query for the pipeline_id).

Say, in use case 2, if one uses a different version of the same notebook, one can query for the notebook id. If one uses different notebooks, one needs to have an idea of what qualifies the same dataset.

---

Overall, these examples show that it may in fact be dangerous to introduce a version identifier that is detached from any semantically more concretely defined entity.

---

We conclude that it's best to drop versioning from the dobject table.

**Comment by sunnyosun** [comment]
I agree with dropping the version.

**Comment by falexwolf** [comment]
- https://github.com/laminlabs/lnschema-core/pull/39
