### ISSUE TITLE
Progress bar for committing data objects needed

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb#261]
It would be really great to understand at what stage the uploading is.

**Comment by falexwolf** [comment]
I agree, could you add this feature?

**Comment by falexwolf** [comment]
Let's discuss about prioritization!

**Comment by Koncopd** [comment]
I am investigating, unfortunately, seems harder to add than i thought.

**Comment by Koncopd** [comment]
Ok, this can be done with fsspec.
