### ISSUE TITLE
Can't import lamindb for instances created without the wetlab schema

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb#366]
There are errors on lamindb import for instances initialized without wetlab schema. I will write details later.

**Comment by Koncopd** [comment]
Or also when trying to the instance even with wetlab schema.
`InvalidRequestError: When initializing mapper mapped class Biometa->wetlab.biometa, expression 'Readout' failed to locate a name ('Readout'). If this is a class name, consider adding this relationship() to the <class 'lnschema_wetlab._core.Biometa'> class after both dependent classes have been defined.`

**Comment by falexwolf** [comment]
- https://github.com/laminlabs/lamindb/pull/367
