### ISSUE TITLE
Implementation of `.add` by fields

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#388]
Could we change this to use `one_or_none()` instead of `all()`? @sunnyosun 
https://github.com/laminlabs/lamindb/blob/23e4d9defd1f761187b7f26275312a4cdeca60e1/lamindb/dev/db/_add.py#L69-L73

**Comment by sunnyosun** [comment]
I can do this, basically, this will mean users won't be able to delete multiple records via this method, which is ok, they can just pass the records.
