### ISSUE TITLE
Large Pandas DataFrames too wide in docs

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#419]
Leads to ugly overlaps with navigation elements.

![image](https://user-images.githubusercontent.com/21954664/209581589-bf23796e-b7ec-452c-abbe-30ca4cc27af5.png)

We also have this issue for the best practices book. We haven't tried out things yet but it might be possible to play around with

`(pd.set_option('display.max_columns', None)`

**Comment by sunnyosun** [comment]
This is resolved with new pydata-sphinx-theme: https://github.com/laminlabs/lndocs/pull/37
