### ISSUE TITLE
Readout lookup does not populate any fields other than EFO ID

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#429]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/16916678/211828019-1bffe3e9-c08c-4aad-abf7-965bb6b02702.png">

Hence, it's going to be hard to search this table! @sunnyosun 

I also saw that several tables in `lnschema_bionty` aren't knowledge tables yet. I'm not clear on whether the Readout table should be a knowledge table! Just noting it down here!

**Comment by sunnyosun** [comment]
See https://github.com/laminlabs/lnschema-bionty/issues/67
