### ISSUE TITLE
Seemingly unfixable db patterns

### ISSUE THREAD

**Issue by samgoodman** [laminlabs/lamindb#464]
I initially created passed an improper DB URI to `lndb.init()`, starting with "mssql://"
This throws an AssertionError : `assert self._db.startswith("postgresql://")`

However, my incorrect DB name gets quietly cached in my .lndb/*.env files, even though` lndb.init()` never completed successfully.

Any subsequent `lndb.init()` calls with a postgreSQL db passed still read the old mysql db from cache, raising more AssertionErrors.

Because `lndb.init()` never completed, neither `lndb.delete()` nor `lndb_setup.set_storage()` work correctly to delete the old instance with the mysql db. 

The only resolution I found was to delete my .lndb/*.env files manually. 

Is there a better user journey I should be taking here?

**Comment by falexwolf** [comment]
Thanks for reporting this! We'll fix this validation issue this week.

The arg in `init()` is typed correctly, but we're not yet erroring, here.
<img width="290" alt="image" src="https://user-images.githubusercontent.com/16916678/215929308-94dbc060-e48d-4d2c-8c73-9fae55a40599.png">

**Comment by falexwolf** [comment]
This is fixed in the upcoming release (tomorrow or so).

Thanks again for reporting, @samgoodman!
