### ISSUE TITLE
Ingesting existing data

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb#498]
I merely put the `paradisi_` image file into the `mytest` folder when running the first notebook of the guide, but it still ended up copying the file rather than just keeping it with its original name.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/16916678/219660577-c94c7454-f185-416f-b79e-e6b945151700.png">

**Comment by sunnyosun** [comment]
I've just tested it extensively with multiple different files, locally and on cloud. I'm pretty sure it doesn't copy the file. Could you show me how you did it?
