### ISSUE TITLE
Ingesting a folder that is not contained in the storage folder of a local instance is not supported

### ISSUE THREAD

**Issue by bpenteado** [laminlabs/lamindb#529]
Ingestion proceeds without error, but because the `._dobjectkey` attribute never gets assigned [in ln.add](https://github.com/laminlabs/lamindb/blob/eaa81de1ba24948080445b03273f7ee28911312a/lamindb/dev/db/_add.py#L237), downstream functionality errors out.

<img width="1117" alt="Screen Shot 2023-03-01 at 3 45 29 PM" src="https://user-images.githubusercontent.com/33378855/222173753-1e91ee28-0e02-4f15-8b85-c73d4375dd8e.png">

**Comment by falexwolf** [comment]
Thanks a ton for reporting, @bpenteado!

@sunnyosun, I think this is quite an important bug, in particular as the current folder doesn't even spell out that the folder must be in the configured storage: https://lamin.ai/docs/faq/ingest-folder

My sense is that, together with @Koncopd, we have to write fine-grained unit tests for the whole storage-related API; and then we'll also cover this case.

For the time being, one could just add a disclaimer to the guide and say "only works for configured storage" (need a better word.

**Comment by sunnyosun** [comment]
Thanks for reporting. It's not a bug, it's not a feature we can easily enable at the moment, uploading a folder to cloud storage is not straightforward.

We'll not enable it for a short time, but will definitely in the long run.

I'll add a warning to it, and erroring behaviors.
