### ISSUE TITLE
Using collapsible code blocks for single line statements

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#603]
https://lamin.ai/docs/guide/files has quite a few collapsible code blocks where only a single line is shown. This to me at least felt more annoying than helpful (at hiding not so important information). I'd just show single line statements

**Comment by sunnyosun** [comment]
OK, the purpose of that was to hide the queries as it maybe a bit confusing for users who haven't understood that yet. But I agree it's a bit ugly to show three times, I'll combine the queries to a single block!
