### ISSUE TITLE
ln.add progressbar

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#604]
While playing around I uploaded some quite big datasets and I'd have wished for an upload progressbar.

**Comment by Zethson** [comment]
It wasn't really updating for me for some reason and this can be way prettier.

**Comment by Koncopd** [comment]
Hm, it should update. Could you please give an example where it doesn't, i will check.

**Comment by Zethson** [comment]
It worked for some, but a few look like:

```
🔶 The IPython instance is empty.cts/bionty/bionty/_dynamic/human_pw_7_74_Pathway___: 0.00
Uploading /home/zeth/PycharmProjects/bionty/bionty/_dynamic/human_pw_7_74_Pathway___: 1.00
```
with only 0 and 1 even though the upload took some time.

In any case, imo a rich progressbar looks nicer.

**Comment by Koncopd** [comment]
Where do i get this file to check?

**Comment by Zethson** [comment]
PMed

**Comment by Zethson** [comment]
There's https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.callbacks.TqdmCallback which makes all of this hella easier and cleaner.

@Koncopd should we transfer this to lndb_storage?

**Comment by Koncopd** [comment]
Yes, i know this ofc, unfortunately this callback didn't work around 4 months ago. Maybe they fixed it but i doubt.
