### ISSUE TITLE
Is coverage from lndb-storage tests missing?

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb#656]
It seems so to me. @falexwolf ?

**Comment by falexwolf** [comment]
Yes, it's not factored into lamindb coverage!

**Comment by falexwolf** [comment]
Because it's a different pytest session, even a different GitHub Actions runner.

**Comment by Koncopd** [comment]
Yeah, then this means that coverage is underestimated now.

**Comment by falexwolf** [comment]
Yes, I think so. It's not optimal and we'll fix this, but not today or tomorrow!
